<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::create([
            'subcategory_id' => 4,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Грибы Эноки',
            'name_kz'        => 'Эноки саңырауқұлақтары',
            'name_en'        => 'Enoki Mushrooms',
            'description_ru' => 'Эноки — это нежные грибы с тонкими белыми ножками и небольшими шляпками, обладающие лёгким сладковатым вкусом и мягкой текстурой. Отлично подходят для супов, салатов и горячих блюд.',
            'description_kz' => 'Эноки саңырауқұлақтары — жұқа, ақ түсті сабағы және кішкентай қалпақшалары бар нәзік саңырауқұлақтар. Олар сорпаға, салатқа және әртүрлі ыстық тағамдарға жақсы үйлеседі.',
            'description_en' => 'Enoki mushrooms are delicate fungi with thin white stems and small caps, offering a mild sweet flavor and tender texture. Perfect for soups, salads, and stir-fries.',
            'price'          => 380,
            'discount'       => 0,
            'photo_url'      => '/storage/products/gribi.webp',
            'weight'         => '1 кг',
            'calories'       => 37,
            'proteins'       => 2.7,
            'fats'           => 0.2,
            'carbohydrates'  => 7.8,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Айсберг',
            'name_kz'        => 'Айсберг салаты',
            'name_en'        => 'Iceberg Lettuce',
            'description_ru' => 'Айсберг — это хрустящий салат с сочными зелёными листьями, отлично подходит для приготовления свежих салатов и бутербродов.',
            'description_kz' => 'Айсберг салаты — қытырлақ, шырынды жапырақтары бар салат, балғын салаттар мен бутербродтарға өте қолайлы.',
            'description_en' => 'Iceberg lettuce is a crunchy, juicy salad green, perfect for fresh salads and sandwiches.',
            'price'          => 400,
            'discount'       => 0,
            'photo_url'      => '/storage/products/iceberg.webp',
            'weight'         => '1 кг',
            'calories'       => 14,
            'proteins'       => 0.9,
            'fats'           => 0.1,
            'carbohydrates'  => 3,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Ассорти',
            'name_kz'        => 'Аралас көк',
            'name_en'        => 'Mixed Greens',
            'description_ru' => 'Ассорти из свежей зелени включает разные виды салатов и трав, наполняя блюда витаминами и ароматом.',
            'description_kz' => 'Аралас көк — түрлі салаттар мен шөптердің қоспасы, тағамдарға дәрумендер мен хош иіс береді.',
            'description_en' => 'A fresh assortment of greens includes various salad leaves and herbs, enriching dishes with vitamins and flavor.',
            'price'          => 500,
            'discount'       => 0,
            'photo_url'      => '/storage/products/assorti.jpg',
            'weight'         => '1 кг',
            'calories'       => 23,
            'proteins'       => 2.0,
            'fats'           => 0.3,
            'carbohydrates'  => 3.5,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Базилик',
            'name_kz'        => 'Базилик',
            'name_en'        => 'Basil',
            'description_ru' => 'Базилик — ароматная зелень с ярким пряным вкусом, часто используется в соусах, салатах и итальянской кухне.',
            'description_kz' => 'Базилик — ерекше хош иісі бар көк, оны тұздықтарда, салаттарда және италиялық тағамдарда жиі қолданады.',
            'description_en' => 'Basil is a fragrant herb with a bright, spicy flavor, often used in sauces, salads, and Italian dishes.',
            'price'          => 500,
            'discount'       => 0,
            'photo_url'      => '/storage/products/bazilik.jpg',
            'weight'         => '1 кг',
            'calories'       => 22,
            'proteins'       => 3.2,
            'fats'           => 0.6,
            'carbohydrates'  => 2.7,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень кинза',
            'name_kz'        => 'Кинза (кориандр)',
            'name_en'        => 'Cilantro',
            'description_ru' => 'Кинза (кориандр) — пряная зелень с ярким ароматом, придаёт особый вкус блюдам и широко используется в восточной кухне.',
            'description_kz' => 'Кинза (кориандр) — хош иісті көк, тағамдарға ерекше дәм беріп, шығыс асханасында жиі қолданылады.',
            'description_en' => 'Cilantro (coriander) is a fragrant herb with a distinct aroma, adding a unique flavor to dishes, commonly used in Eastern cuisine.',
            'price'          => 400,
            'discount'       => 0,
            'photo_url'      => '/storage/products/kinza.jpg',
            'weight'         => '1 кг',
            'calories'       => 23,
            'proteins'       => 2.1,
            'fats'           => 0.5,
            'carbohydrates'  => 3.6,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Лола Роса',
            'name_kz'        => 'Лолло росса салаты',
            'name_en'        => 'Lollo Rossa Lettuce',
            'description_ru' => 'Лола Роса — сорт салата с ярко-красными волнистыми листьями и мягким вкусом. Идеально для свежих салатов.',
            'description_kz' => 'Лолло росса салаты — қызыл толқынды жапырақтары бар салат, нәзік дәмі бар және салаттарда өте қолайлы.',
            'description_en' => 'Lollo Rossa is a lettuce variety with bright red, frilly leaves and a mild flavor, perfect for fresh salads.',
            'price'          => 500,
            'discount'       => 0,
            'photo_url'      => '/storage/products/lolla-rossa.jpg',
            'weight'         => '1 кг',
            'calories'       => 16,
            'proteins'       => 1.3,
            'fats'           => 0.2,
            'carbohydrates'  => 3.0,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень лук зеленый',
            'name_kz'        => 'Жасыл пияз',
            'name_en'        => 'Green Onions',
            'description_ru' => 'Зелёный лук — молодые побеги репчатого лука, отличается мягким вкусом. Часто используется для украшения и добавления свежести блюдам.',
            'description_kz' => 'Жасыл пияз — басты пияздың жас өскіндері, жұмсақ дәмі бар. Тағамдарды әрлеу және оларға балғындық беру үшін қолданылады.',
            'description_en' => 'Green onions are young shoots of bulb onions with a mild flavor, often used for garnishing and adding freshness to dishes.',
            'price'          => 450,
            'discount'       => 0,
            'photo_url'      => '/storage/products/lukzelenii.jpg',
            'weight'         => '1 кг',
            'calories'       => 32,
            'proteins'       => 1.8,
            'fats'           => 0.2,
            'carbohydrates'  => 7.3,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень мята',
            'name_kz'        => 'Жалбыз',
            'name_en'        => 'Mint',
            'description_ru' => 'Мята — освежающая зелень с ярким ментоловым ароматом, часто используется в напитках, десертах и соусах.',
            'description_kz' => 'Жалбыз — сергітетін хош иісі бар көк, сусындарда, десерттерде және тұздықтарда жиі қолданылады.',
            'description_en' => 'Mint is a refreshing herb with a strong menthol aroma, commonly used in beverages, desserts, and sauces.',
            'price'          => 500,
            'discount'       => 0,
            'photo_url'      => '/storage/products/myata.webp',
            'weight'         => '1 кг',
            'calories'       => 44,
            'proteins'       => 3.3,
            'fats'           => 0.7,
            'carbohydrates'  => 8.4,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень петрушка',
            'name_kz'        => 'Ақжелкен',
            'name_en'        => 'Parsley',
            'description_ru' => 'Петрушка — универсальная зелень с насыщенным ароматом, богата витаминами и минералами. Хорошо подходит к салатам, супам и соусам.',
            'description_kz' => 'Ақжелкен — хош иісті, дәрумендер мен минералдарға бай көк. Салаттарда, сорпаларда және тұздықтарда жиі қолданылады.',
            'description_en' => 'Parsley is a versatile herb with a rich aroma, high in vitamins and minerals. Perfect for salads, soups, and sauces.',
            'price'          => 380,
            'discount'       => 0,
            'photo_url'      => '/storage/products/petrushka.webp',
            'weight'         => '1 кг',
            'calories'       => 36,
            'proteins'       => 3.0,
            'fats'           => 0.8,
            'carbohydrates'  => 6.3,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень петрушка кудрявая',
            'name_kz'        => 'Бұйра ақжелкен',
            'name_en'        => 'Curly Parsley',
            'description_ru' => 'Кудрявая петрушка отличается декоративными листьями и ярким ароматом. Часто используется для украшения блюд.',
            'description_kz' => 'Бұйра ақжелкен әдемі бұйра жапырақтары және хош иісімен ерекшеленеді, көбіне тағамдарды безендіру үшін қолданылады.',
            'description_en' => 'Curly parsley has decorative, frilly leaves and a bright aroma, often used for garnishing dishes.',
            'price'          => 500,
            'discount'       => 0,
            'photo_url'      => '/storage/products/kudryavaya.png',
            'weight'         => '1 кг',
            'calories'       => 36,
            'proteins'       => 3.0,
            'fats'           => 0.8,
            'carbohydrates'  => 6.3,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Салат Микс',
            'name_kz'        => 'Салат миксі',
            'name_en'        => 'Salad Mix',
            'description_ru' => 'Салат Микс — это сочетание разных видов салатов и пряных трав, добавляющее разнообразие во вкус и внешний вид блюд.',
            'description_kz' => 'Салат миксі — түрлі салаттар мен хош иісті шөптердің қосындысы, тағамның дәмі мен көрінісін әрлейді.',
            'description_en' => 'Salad Mix is a combination of various leafy greens and herbs, adding variety in taste and appearance.',
            'price'          => 700,
            'discount'       => 0,
            'photo_url'      => '/storage/products/miks.webp',
            'weight'         => '1 кг',
            'calories'       => 25,
            'proteins'       => 1.8,
            'fats'           => 0.3,
            'carbohydrates'  => 4.0,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Салат Рукола',
            'name_kz'        => 'Руккола',
            'name_en'        => 'Arugula',
            'description_ru' => 'Рукола — салат с пикантным, слегка горьковатым вкусом и ореховым ароматом. Часто используется в итальянской кухне.',
            'description_kz' => 'Руккола — ащылау, жаңғақ хош иісі бар салат, италиялық тағамдарда жиі қолданылады.',
            'description_en' => 'Arugula is a peppery, slightly bitter salad green with a nutty aroma, commonly used in Italian cuisine.',
            'price'          => 700,
            'discount'       => 0,
            'photo_url'      => '/storage/products/rukkola.webp',
            'weight'         => '1 кг',
            'calories'       => 25,
            'proteins'       => 2.6,
            'fats'           => 0.7,
            'carbohydrates'  => 3.7,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Салатный лист',
            'name_kz'        => 'Жапырақты салат',
            'name_en'        => 'Leaf Lettuce',
            'description_ru' => 'Салатный лист — это нежные зелёные листья, идеально подходящие для приготовления свежих салатов и украшения блюд.',
            'description_kz' => 'Жапырақты салат — жұмсақ жасыл жапырақтары бар, балғын салаттар жасауға және тағамды әсемдеуге ыңғайлы.',
            'description_en' => 'Leaf lettuce is a tender green leaf, perfect for fresh salads and garnishing dishes.',
            'price'          => 550,
            'discount'       => 0,
            'photo_url'      => '/storage/products/list.jpg',
            'weight'         => '1 кг',
            'calories'       => 15,
            'proteins'       => 1.4,
            'fats'           => 0.2,
            'carbohydrates'  => 2.9,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Сельдерея листья',
            'name_kz'        => 'Сельдерей жапырақтары',
            'name_en'        => 'Celery Leaves',
            'description_ru' => 'Листья сельдерея — ароматная зелень с лёгкой горчинкой, богата витаминами. Хорошо сочетается с овощными блюдами и супами.',
            'description_kz' => 'Сельдерей жапырақтары — хош иісті көк, аздап ащылау дәмі бар, көкөніс тағамдары мен сорпаларға сай келеді.',
            'description_en' => 'Celery leaves are aromatic greens with a slight bitterness, rich in vitamins, pairing well with vegetable dishes and soups.',
            'price'          => 250,
            'discount'       => 0,
            'photo_url'      => '/storage/products/listya.jpg',
            'weight'         => '1 кг',
            'calories'       => 12,
            'proteins'       => 0.7,
            'fats'           => 0.2,
            'carbohydrates'  => 2.2,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Стебли сельдерей',
            'name_kz'        => 'Сельдерей сабағы',
            'name_en'        => 'Celery Stalks',
            'description_ru' => 'Стебли сельдерея — это хрустящие побеги с освежающим ароматом, часто используются в салатах, смузи и для перекусов.',
            'description_kz' => 'Сельдерей сабағы — қытырлақ, балғын хош иісі бар, салаттарда, смузилерде және жеңіл тамақтарда пайдаланады.',
            'description_en' => 'Celery stalks are crisp shoots with a fresh aroma, commonly used in salads, smoothies, and as a healthy snack.',
            'price'          => 780,
            'discount'       => 0,
            'photo_url'      => '/storage/products/stebli.jpg',
            'weight'         => '1 кг',
            'calories'       => 14,
            'proteins'       => 0.7,
            'fats'           => 0.1,
            'carbohydrates'  => 3.0,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень укроп',
            'name_kz'        => 'Аскөк',
            'name_en'        => 'Dill',
            'description_ru' => 'Укроп — это ароматная зелень с освежающим вкусом, часто используется для солений, соусов и рыбных блюд.',
            'description_kz' => 'Аскөк — хош иісті көк, тұздалған тағамдарда, тұздықтарда және балық тағамдарында кең қолданылады.',
            'description_en' => 'Dill is an aromatic herb with a refreshing flavor, often used for pickles, sauces, and fish dishes.',
            'price'          => 450,
            'discount'       => 0,
            'photo_url'      => '/storage/products/ukrop.jpg',
            'weight'         => '1 кг',
            'calories'       => 43,
            'proteins'       => 3.5,
            'fats'           => 1.1,
            'carbohydrates'  => 7.0,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Шпинат',
            'name_kz'        => 'Шпинат',
            'name_en'        => 'Spinach',
            'description_ru' => 'Шпинат — листовая зелень с мягким вкусом и богатым содержанием витаминов и минералов. Идеален для салатов, супов и горячих блюд.',
            'description_kz' => 'Шпинат — нәзік дәмі бар жапырақты көк, дәрумендер мен минералдарға бай. Салаттарда, сорпаларда және ыстық тағамдарда қолданылады.',
            'description_en' => 'Spinach is a leafy green with a mild taste, rich in vitamins and minerals. Ideal for salads, soups, and cooked dishes.',
            'price'          => 500,
            'discount'       => 0,
            'photo_url'      => '/storage/products/shpinat.webp',
            'weight'         => '1 кг',
            'calories'       => 23,
            'proteins'       => 2.9,
            'fats'           => 0.4,
            'carbohydrates'  => 3.6,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 3,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Зелень Щавель',
            'name_kz'        => 'Қымыздық',
            'name_en'        => 'Sorrel',
            'description_ru' => 'Щавель — кислая зелень с освежающим вкусом, широко используется в супах (зелёный борщ), салатах и соусах.',
            'description_kz' => 'Қымыздық — қышқыл, сергітетін дәмі бар көк, көк сорпада, салаттарда және тұздықтарда жиі қолданылады.',
            'description_en' => 'Sorrel is a tangy green with a refreshing flavor, often used in soups (green borscht), salads, and sauces.',
            'price'          => 350,
            'discount'       => 0,
            'photo_url'      => '/storage/products/shavel.web',
            'weight'         => '1 кг',
            'calories'       => 22,
            'proteins'       => 2.0,
            'fats'           => 0.3,
            'carbohydrates'  => 3.2,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 2,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Овощи капуста цветная',
            'name_kz'        => 'Түсті қырыққабат',
            'name_en'        => 'Cauliflower',
            'description_ru' => 'Цветная капуста — нежные соцветия с мягким вкусом, отлично подходит для запекания, жарки и приготовления в кляре.',
            'description_kz' => 'Түсті қырыққабат — жұмсақ дәмі бар гүлшоғырлар, оны қуыруға, пісіруге және клярда дайындауға болады.',
            'description_en' => 'Cauliflower features tender florets with a mild flavor, perfect for roasting, frying, or cooking in batter.',
            'price'          => 1300,
            'discount'       => 0,
            'photo_url'      => '/storage/products/kapustacvet.jpg',
            'weight'         => '1 кг',
            'calories'       => 25,
            'proteins'       => 1.9,
            'fats'           => 0.3,
            'carbohydrates'  => 5.0,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 2,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Овощи Редиска',
            'name_kz'        => 'Шомыр',
            'name_en'        => 'Radish',
            'description_ru' => 'Редиска — это хрустящий корнеплод с острым, слегка горьковатым вкусом, часто используется в салатах.',
            'description_kz' => 'Шомыр — ащылау дәмі бар қытырлақ тамыржеміс, салаттарға жиі қосылады.',
            'description_en' => 'Radish is a crunchy root vegetable with a sharp, slightly bitter taste, commonly used in salads.',
            'price'          => 400,
            'discount'       => 0,
            'photo_url'      => '/storage/products/rediska.jpg',
            'weight'         => '1 кг',
            'calories'       => 16,
            'proteins'       => 0.7,
            'fats'           => 0.1,
            'carbohydrates'  => 3.4,
            'is_active'      => 1,
        ]);

        Product::create([
            'subcategory_id' => 2,
            'manufacturer'   => 'ТОО "Abricoz", Казахстан',
            'name_ru'        => 'Овощи черри',
            'name_kz'        => 'Шие қызанақтар',
            'name_en'        => 'Cherry Tomatoes',
            'description_ru' => 'Томаты черри — маленькие сладкие помидоры, идеально подходят для салатов, закусок и украшения блюд.',
            'description_kz' => 'Шие қызанақтар — кішкентай тәтті қызанақтар, салаттарда, тіскебасарларда және тағамдарды сәндеуге таптырмас.',
            'description_en' => 'Cherry tomatoes are small, sweet tomatoes, perfect for salads, appetizers, and garnishing dishes.',
            'price'          => 700,
            'discount'       => 0,
            'photo_url'      => '/storage/products/cherri.webp',
            'weight'         => '1 кг',
            'calories'       => 18,
            'proteins'       => 0.9,
            'fats'           => 0.2,
            'carbohydrates'  => 3.6,
            'is_active'      => 1,
        ]);

        $products = Product::all();
        foreach ($products as $product) {
            $discountedPrice = $product->price - ($product->price * $product->discount / 100);
            $product->price_with_discount = $discountedPrice;
            $product->save();
        }
    }
}
