version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/

  nginx:
    image: nginx:latest
    ports:
      - "443:443"
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
      - ./_docker/nginx/ssl/:/etc/ssl/
    depends_on:
      - app
